### ISSUE TITLE
Feature request: Give a title for a groove

### ISSUE THREAD

**Issue by aonghas43** [mooseling/BananaDrum#7]
If Banana Drum is used as a practice aid, then links to a complete groove/beat will be shared.

It would be useful if these could have a free text title field which the sharing URL also encapsulates, for example "London School: Break 1".

This would also help for printed output from the app

**Comment by mooseling** [comment]
This is actually the next thing I intend to do! It was suggested to me by someone else as well. I think it's a great idea.

**Comment by mooseling** [comment]
This is now released!
